CREATE DATABASE IF NOT EXISTS expensetracker;
USE expensetracker;


CREATE TABLE IF NOT EXISTS expenses (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255) NOT NULL,
amount DECIMAL(10,2) NOT NULL,
category VARCHAR(100) DEFAULT 'General',
expense_date DATE NOT NULL,
note VARCHAR(500),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);